apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  # property-like keys; each key maps to a simple value
  backend_host: <ip>
  backend_port: <port>
  backend_api_token: <token>
  github_token: <githb_token>
