apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    product: webhook-gateway
  name: webhook-gateway-tmp
  namespace: default
  resourceVersion: "11171"
  selfLink: /apis/apps/v1/namespaces/default/deployments/webhook-gateway-tmp
  uid: 5ab9a48c-cc55-4096-b357-5f53e8a6139e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      product: webhook-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        product: webhook-gateway
    spec:
      containers:
      - image: webhook-gateway-tmp:latest
        imagePullPolicy: IfNotPresent
        name: webhook-gateway
        ports:
        - containerPort: 31430
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

